spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/alamda
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug

  #Google
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 269339707834-ogp51le99ahmtmbbd7fltemn4cjh0a43.apps.googleusercontent.com
            client-secret: ???
            scope: profile, email

jwt:
  issuer: dalamz@dalamz.com
  secret_key: ???